// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueepzqmjueozyhbjcrzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlZXB6cW1qdWVvenloYmpjcnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDM1MDEsImV4cCI6MjA3MzAxOTUwMX0.44_Qy2IoEtdMx7K9JIYljzLe7kJDQEm0NBh42whPLZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});